### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by minhnimble** [SeintApril/Survey#12]
The app crashes when users try to input invalid credentials in the Login page. Please help check and fix this problem and handle it gracefully instead of terminating the application and crash like this 😅

![Screen Shot 2022-01-10 at 09 49 18](https://user-images.githubusercontent.com/70877098/148726110-46d07d11-9891-4fa9-b268-7bd3988f2970.png)

**Comment by SeintApril** [comment]
hee hee. I will fixed it 😄

**Comment by minhnimble** [comment]
The crash issue is resolved, nice work 🎉
